version: "3.9"
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config:/prometheus
      - ./data/prometheus:/data
    command:
      - "--config.file=/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/data"
    ports:
      - 9090:9090
  app:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - 8080:8080
      - 9464:9464
    volumes:
      - .:/app
    depends_on:
      - zipkin
      - prometheus
